import type { Config } from "tailwindcss";

// Design tokens sourced from /kutoharjo_umkm_hub_identity/DESIGN.md
const config: Config = {
  darkMode: "class",
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fc",
        "surface-dim": "#d8dadd",
        "surface-bright": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface-container-highest": "#e0e3e6",
        "on-surface": "#191c1e",
        "on-surface-variant": "#45464e",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f4",
        outline: "#76767f",
        "outline-variant": "#c6c6d0",
        "surface-tint": "#0F172A",
        primary: "#0F172A",
        "on-primary": "#ffffff",
        "primary-container": "#1E293B",
        "on-primary-container": "#94A3B8",
        "inverse-primary": "#CBD5E1",
        secondary: "#10B981",
        "on-secondary": "#ffffff",
        "secondary-container": "#059669",
        "on-secondary-container": "#ECFDF5",
        tertiary: "#334155",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#475569",
        "on-tertiary-container": "#F1F5F9",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#F8FAFC",
        "on-background": "#0F172A",
        "surface-variant": "#E2E8F0",
      },
      borderRadius: {
        sm: "0.5rem",
        DEFAULT: "1rem",
        md: "1.5rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "120px",
      },
      fontFamily: {
        "display-lg": ["var(--font-manrope)"],
        "headline-lg": ["var(--font-manrope)"],
        "headline-md": ["var(--font-manrope)"],
        "headline-lg-mobile": ["var(--font-manrope)"],
        "body-lg": ["var(--font-hanken)"],
        "body-md": ["var(--font-hanken)"],
        "label-md": ["var(--font-hanken)"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", fontWeight: "800", letterSpacing: "-0.02em" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1.4", fontWeight: "600", letterSpacing: "0.01em" }],
      },
    },
  },
  plugins: [],
};

export default config;
